### ISSUE TITLE
Support Nested Ragged Tensors

### ISSUE THREAD

**Issue by mmcdermott** [huggingface/safetensors#402]
### Feature request

It would be great if safetensors could efficiently store/load ragged and nested ragged tensors. E.g., I want to be able to do something like:

```python
nested_ragged_tensor = [[torch.Tensor([1, 2]), torch.Tensor([3])], [torch.Tensor([1, 2, 4, 5, 6])]]
safetensor.torch.save_file(nested_ragged_tensor, "file.pt")
```

And have it work efficiently by internally storing the raw values in contiguous (flattened) form and tensors corresponding to the nested set of lengths observed so that the data can be reconstructed on the fly.

### Motivation

For models in the ESGPT format (https://eventstreamml.readthedocs.io/en/dev/usage.html#batch-representation-eventstream-data-pytorchbatch) batches are constructed of nested ragged tensors of observed measurements per time point per patient, and the saving/loading of these tensors is challenging.

### Your contribution

I do not have immediate bandwidth to submit a PR, but I do have a technical design for this functionality that I think would work given by directly storing the contiguous, flattened values as well as a set of tensors of observed lengths at each level of nesting in the tensor. Happy to outline more if this functionality would be of interest to safetensors.

**Comment by mmcdermott** [comment]
I've implemented this (https://github.com/mmcdermott/nested_ragged_tensors), which I think could be a solution here.

**Comment by Narsil** [comment]
I'm not sure I understand. you want unnamed tensors ? 

I don´t think we want to add that, just use `{"0": xxx, "1", ...}` if you really want a list like thing (or nested if you want).

**Comment by mmcdermott** [comment]
No, not unnamed tensors, ragged (aka jagged) tensors. 

Consider a dataset where each sample consists of a document (each document is of varying lengths). With current tools, if you want to store a tokenized version of that dataset, you can either pad all documents to the same length and store it as a tensor or store it as a list of separate documents. Neither of these solutions is particularly efficient.

Another option is to store two tensors: One, a flat tensor of all the token ids across all documents concatenated, and another tensor with the lengths of the documents. The latter will add a negligible storage cost but permit you to restore the 2D shape directly.

This problem is even more involved if your dataset consists of sequences of documents, where the documents and sequences are both of varying lengths. This is common in, for example, datasets of medical notes. Each patient has a sequence of notes during their health stay, where every sequence and every document are of varying lengths. Again, you can store this efficiently with a flat tensor of tokens then a tensor of sequence lengths, then a flattened tensor of document lengths. These structures I'm calling "nested ragged tensors", and they are what I'd like to store and load efficiently.

**Comment by Narsil** [comment]
And cannot you do just that using some naming convention ?

I still fail to see the benefit of having anything like that written on disk. Also ragged tensor support on PT is flaky (not a lot of ops are supported) and so it is in TF.

Having several tensors of various shapes seems just as easy, and will fit the bill here. (And you use names to recover your arbitrarily nested hierachy of object, whether they are list, dics, or dicts of lists of lists of dicts).

**Comment by mmcdermott** [comment]
I tried what you are suggesting and it is significantly more computationally expensive on all axes. File sizes on disk are larger, read/write times are slower, and iterating through the dataset when in a named, dictionary form is _much_ slower. 

That said, I appreciate the hesitation to add support for a new tensor organization to a low-level library. Feel free to close this issue for now and I will publish my library (https://github.com/mmcdermott/nested_ragged_tensors) separately on pypi to support this kind of data structure.

**Comment by Narsil** [comment]
> File sizes on disk are larger, 

Care to share numbers ? Unless you have >10k tensors I don' t think the header size should be any significant.

> read/write times are slower,

Again numbers ?

> iterating through the dataset when in a named, dictionary form is much slower.

I seriously doubt that. Dictionary has nothing to do with read speeds. What matter for read speed is making sequential reads. In ML tensors usually exceed page size meaning that there's going to be little to no benefit in the read order (on an SSD, I don't think HDD are that much used anymore). 

Also since we're memmapping the file anyway, the OS will make reads extremely efficient it's hard to ever see the access pattern being displayed in any meaningful way.

Looked briefly at your lib, definitely seems like it' s many super small tensors https://github.com/mmcdermott/nested_ragged_tensors/blob/main/performance_tests/configs/dataset_spec/mimic.yaml which is definitely the intended use case for this lib.

Looking at the number you show, it seems the header is ~half the size of the file, which is indeed insanely big.

Glad you found something that worked better for you.

**Comment by mmcdermott** [comment]
The numbers are all in the REWADME of my library. The option referring to
"safetensors" is what you suggested. If my numbers are incorrect for some
reason feel free to let me know; I'd love to be proven wrong.

**Comment by Narsil** [comment]
> Looking at the number you show, it seems the header is ~half the size of the file, which is indeed insanely big.

Sorry I read your numbers after writing the start of my answer. I'm guessing from what I see that it' s simply the shear number of tensors vastly outweighs their size, meaning the parsing of the JSON header is the issue, nothing linked with zero-copy or anything.

Since having such a large header is definitely not intended, it most likely explains the differences in speed. It's very far from what safetensors is currently good at.

Maybe take a look at parquet too, it's intended for datasets and might be more suitable for your use case.

**Comment by mmcdermott** [comment]
Ahh, that makes more sense. Yeah, that is my expectation of the issue too.
This isn't in the numbers in the library I showed there, but I did
initially start with parquet actually and it was also a fair bit slower.
Time pending maybe I'll add it to the performance testing and see. I also
think there is another point of bias in my comparisons because
fundamentally once the data is sliced from getitem, I think the collate
portion could be made to be identical across all of the "non-pre-padded"
methods, but right now the nested ragged tensors collate function (the one
I implemented in the core library) is much faster and I don't fully
understand why. If you have any thoughts on that I'd be very grateful, but
regardless thank you again for the comments and thoughts so far.

**Comment by Narsil** [comment]
> I think the collate
> portion could be made to be identical across all of the "non-pre-padded"
> methods, but right now the nested ragged tensors collate function (the one
> I implemented in the core library) is much faster and I don't fully

I don' t have time to look deeply, but most likely one is doing a copy and not the other. That's usually the only reason.
